<a href="https://colab.research.google.com/github/ellenwang995/week2_pandas/blob/main/Session_2_Student_Worksheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📊 Session 2 — Student Worksheet (Pandas + Plotly)
Work in small groups. Find a CSV dataset on GitHub, load it in Colab, and adapt commands from the workbook.
Be ready to walk through your code at the end.

## Part 1 — Find a Dataset (GitHub)

In [1]:
csv_url = "https://raw.githubusercontent.com/owid/energy-data/refs/heads/master/owid-energy-data.csv"
csv_url

'https://raw.githubusercontent.com/owid/energy-data/refs/heads/master/owid-energy-data.csv'

## Part 2 — Load & Inspect

In [2]:
import pandas as pd

# Corrected URL to the raw CSV data
csv_url = "https://raw.githubusercontent.com/owid/energy-data/e93768587041dbaa2f0ea0b66af616b48c7e7364/owid-energy-data.csv"

energy = pd.read_csv(csv_url)
rows, cols = energy.shape
rows, cols

(23195, 130)

In [3]:
energy_1 = pd.DataFrame(energy)
energy_1

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,ASEAN (Ember),2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
1,ASEAN (Ember),2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
2,ASEAN (Ember),2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
3,ASEAN (Ember),2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
4,ASEAN (Ember),2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23190,Zimbabwe,2020,ZWE,15526837.0,2.317871e+10,NaN,0.0,0.0,0.0,6.440,...,0.298,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
23191,Zimbabwe,2021,ZWE,15797165.0,2.514009e+10,NaN,0.0,0.0,0.0,6.963,...,0.233,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
23192,Zimbabwe,2022,ZWE,16069010.0,2.590159e+10,NaN,0.0,0.0,0.0,6.845,...,0.336,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
23193,Zimbabwe,2023,ZWE,16340778.0,NaN,NaN,0.0,0.0,0.0,7.344,...,0.361,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
23194,Zimbabwe,2024,ZWE,16634317.0,NaN,NaN,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
energy_df = energy_1.fillna(0)

In [5]:
energy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23195 entries, 0 to 23194
Columns: 130 entries, country to wind_share_energy
dtypes: float64(127), int64(1), object(2)
memory usage: 23.0+ MB

In [6]:
energy_df.dtypes

country                    object
year                        int64
iso_code                   object
population                float64
gdp                       float64
                           ...
wind_elec_per_capita      float64
wind_electricity          float64
wind_energy_per_capita    float64
wind_share_elec           float64
wind_share_energy         float64
Length: 130, dtype: object

In [7]:
energy_df.head(10)

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,ASEAN (Ember),2000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.000,0.0
1,ASEAN (Ember),2001,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.000,0.0
2,ASEAN (Ember),2002,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.000,0.0
3,ASEAN (Ember),2003,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.000,0.0
4,ASEAN (Ember),2004,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.000,0.0
5,ASEAN (Ember),2005,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.02,0.0,0.004,0.0
6,ASEAN (Ember),2006,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.007,0.0,0.0,0.0,0.0,0.0,0.05,0.0,0.009,0.0
7,ASEAN (Ember),2007,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.007,0.0,0.0,0.0,0.0,0.0,0.06,0.0,0.010,0.0
8,ASEAN (Ember),2008,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.007,0.0,0.0,0.0,0.0,0.0,0.06,0.0,0.010,0.0
9,ASEAN (Ember),2009,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.006,0.0,0.0,0.0,0.0,0.0,0.07,0.0,0.011,0.0

In [8]:
energy_df.sample(50)

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
18267,Saint Vincent and the Grenadines,2012,VCT,108706.0,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
17946,Romania,1996,ROU,22541865.0,1.465139e+11,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
17824,Reunion,1998,REU,744022.0,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
396,Africa (Ember),2018,0,0.0,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.992,0.000,0.000,0.000,0.000,0.000,14.880,0.000,1.738,0.000
15247,OECD (Shift),1976,0,0.0,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
7588,Finland,1988,FIN,4946577.0,1.268515e+11,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
1175,Armenia,2016,ARM,2918753.0,2.952232e+10,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
6928,Eurasia (Shift),2008,0,0.0,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2136,Bangladesh,1940,BGD,36071677.0,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
10357,Italy,2013,ITA,60653828.0,2.010255e+12,-8.041,-1.255,236.555,14.348,281.598,...,7.548,2.985,11.113,3.545,38.100,245.656,14.900,628.151,5.209,2.060
6261,Ecuador,1978,ECU,7736138.0,4.728827e+10,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2442,Belgium,1957,BEL,8931814.0,9.306427e+10,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
7522,Fiji,1981,FJI,657421.0,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
20369,Tanzania,2003,TZA,37089505.0,5.082460e+10,0.000,0.000,0.000,0.000,1.348,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
16626,Other Western Africa (EI),1991,0,0.0,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
19956,Switzerland,1998,CHE,7110242.0,2.879854e+11,0.000,0.000,0.000,0.000,0.000,...,0.013,0.006,50.000,0.003,0.008,0.422,0.003,1.172,0.005,0.002
19165,South America,2024,0,435610672.0,0.000000e+00,3.248,9.585,699.533,304.724,0.000,...,0.000,3.275,13.327,41.511,352.984,0.000,0.000,810.321,0.000,4.662
1669,Australia,1976,AUS,14046705.0,3.007557e+11,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2190,Bangladesh,1994,BGD,120343133.0,1.374327e+11,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
17471,Poland,2015,POL,38266267.0,9.360438e+11,-6.456,-0.522,197.784,7.568,259.759,...,0.037,0.013,41.417,7.952,27.489,283.801,10.860,718.351,6.610,2.498
1401,Asia (Ember),2010,0,0.0,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.070,0.000,0.000,0.000,0.000,0.000,74.810,0.000,0.916,0.000
12954,Morocco,1944,MAR,8124032.0,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
4619,Colombia,1947,COL,10913579.0,3.592218e+10,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
13583,Netherlands,1996,NLD,15639984.0,4.942068e+11,0.000,0.000,0.000,0.000,83.120,...,0.000,0.001,37.855,0.333,1.214,28.133,0.440,77.614,0.523,0.119
7991,Gabon,2003,GAB,1382304.0,1.471715e+10,0.000,0.000,0.000,0.000,7.234,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
21732,United States,1936,USA,125322686.0,1.359902e+12,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
17870,Romania,1920,ROU,12403390.0,1.312598e+10,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
11362,Low-income countries,1962,0,142711478.0,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
15909,Other Asia Pacific (EI),1986,0,0.0,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
7586,Finland,1986,FIN,4918203.0,1.161536e+11,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
32,Afghanistan,1907,AFG,5106495.0,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
21504,United Arab Emirates,1958,ARE,118728.0,3.031030e+09,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
8337,Ghana,2022,GHA,33149102.0,1.454319e+11,0.000,0.000,0.000,0.000,0.603,...,0.689,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2206,Bangladesh,2010,BGD,152201922.0,4.000878e+11,0.000,0.000,0.000,0.000,0.000,...,0.171,0.046,0.000,-0.000,0.013,0.000,0.000,0.087,0.000,0.005
2777,Bolivia,1991,BOL,7280258.0,2.430099e+10,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
1100,Argentina,1974,ARG,25461303.0,3.406864e+11,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
5709,Denmark,1972,DNK,4991527.0,1.077137e+11,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
20740,Tunisia,1912,TUN,2232478.0,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
3228,Brunei,1991,BRN,262551.0,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2328,Barbados,2007,BRB,271250.0,3.642718e+09,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
16752,Pakistan,1992,PAK,123546809.0,3.278143e+11,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
16437,Other South America (EI),1982,0,0.0,0.000000e+00,109.523,0.053,0.000,0.102,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
15467,OPEC (Shift),1975,0,0.0,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
6122,Eastern Africa (EI),2008,0,0.0,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.028,0.013,45.963,0.013,0.043,0.000,0.016,0.000,0.025,0.011
17217,Peru,2011,PER,29304035.0,2.447119e+11,6.856,0.155,82.565,2.419,23.205,...,0.000,0.000,0.000,-0.000,0.003,0.000,0.000,0.106,0.000,0.001
14070,Nigeria,1960,NGA,45053744.0,5.430256e+10,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
20046,Syria,1963,SYR,5110417.0,2.923472e+10,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
13625,Netherlands Antilles,1978,ANT,168250.0,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
6505,Equatorial Guinea,1992,GNQ,510728.0,1.054728e+09,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
16720,Pakistan,1960,PAK,45709272.0,5.194889e+10,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000

In [9]:
print(energy_df.columns)

Index(['country', 'year', 'iso_code', 'population', 'gdp',
       'biofuel_cons_change_pct', 'biofuel_cons_change_twh',
       'biofuel_cons_per_capita', 'biofuel_consumption',
       'biofuel_elec_per_capita',
       ...
       'solar_share_elec', 'solar_share_energy', 'wind_cons_change_pct',
       'wind_cons_change_twh', 'wind_consumption', 'wind_elec_per_capita',
       'wind_electricity', 'wind_energy_per_capita', 'wind_share_elec',
       'wind_share_energy'],
      dtype='object', length=130)

## Part 3 — Explore & Clean

In [10]:
energy_df[energy_df.duplicated(keep=False)]

Empty DataFrame
Columns: [country, year, iso_code, population, gdp, biofuel_cons_change_pct, biofuel_cons_change_twh, biofuel_cons_per_capita, biofuel_consumption, biofuel_elec_per_capita, biofuel_electricity, biofuel_share_elec, biofuel_share_energy, carbon_intensity_elec, coal_cons_change_pct, coal_cons_change_twh, coal_cons_per_capita, coal_consumption, coal_elec_per_capita, coal_electricity, coal_prod_change_pct, coal_prod_change_twh, coal_prod_per_capita, coal_production, coal_share_elec, coal_share_energy, electricity_demand, electricity_demand_per_capita, electricity_generation, electricity_share_energy, energy_cons_change_pct, energy_cons_change_twh, energy_per_capita, energy_per_gdp, fossil_cons_change_pct, fossil_cons_change_twh, fossil_elec_per_capita, fossil_electricity, fossil_energy_per_capita, fossil_fuel_consumption, fossil_share_elec, fossil_share_energy, gas_cons_change_pct, gas_cons_change_twh, gas_consumption, gas_elec_per_capita, gas_electricity, gas_energy_per_capita, gas_prod_change_pct, gas_prod_change_twh, gas_prod_per_capita, gas_production, gas_share_elec, gas_share_energy, greenhouse_gas_emissions, hydro_cons_change_pct, hydro_cons_change_twh, hydro_consumption, hydro_elec_per_capita, hydro_electricity, hydro_energy_per_capita, hydro_share_elec, hydro_share_energy, low_carbon_cons_change_pct, low_carbon_cons_change_twh, low_carbon_consumption, low_carbon_elec_per_capita, low_carbon_electricity, low_carbon_energy_per_capita, low_carbon_share_elec, low_carbon_share_energy, net_elec_imports, net_elec_imports_share_demand, nuclear_cons_change_pct, nuclear_cons_change_twh, nuclear_consumption, nuclear_elec_per_capita, nuclear_electricity, nuclear_energy_per_capita, nuclear_share_elec, nuclear_share_energy, oil_cons_change_pct, oil_cons_change_twh, oil_consumption, oil_elec_per_capita, oil_electricity, oil_energy_per_capita, oil_prod_change_pct, oil_prod_change_twh, oil_prod_per_capita, oil_production, oil_share_elec, oil_share_energy, other_renewable_consumption, other_renewable_electricity, other_renewable_exc_biofuel_electricity, other_renewables_cons_change_pct, other_renewables_cons_change_twh, other_renewables_elec_per_capita, other_renewables_elec_per_capita_exc_biofuel, ...]
Index: []

[0 rows x 130 columns]

In [11]:
energy_df['year_dt'] = pd.to_datetime(energy_df['year'], format='%Y')
energy_df['year_dt']

0       2000-01-01
1       2001-01-01
2       2002-01-01
3       2003-01-01
4       2004-01-01
           ...
23190   2020-01-01
23191   2021-01-01
23192   2022-01-01
23193   2023-01-01
23194   2024-01-01
Name: year_dt, Length: 23195, dtype: datetime64[ns]

In [12]:
energy_df["biofuel_consumption"]

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
23190    0.0
23191    0.0
23192    0.0
23193    0.0
23194    0.0
Name: biofuel_consumption, Length: 23195, dtype: float64

In [13]:
energy_df_yr = energy_df[energy_df['year'] >=1995]

In [14]:
energy_df_yr

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy,year_dt
0,ASEAN (Ember),2000,0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2000-01-01
1,ASEAN (Ember),2001,0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2001-01-01
2,ASEAN (Ember),2002,0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2002-01-01
3,ASEAN (Ember),2003,0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2003-01-01
4,ASEAN (Ember),2004,0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2004-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23190,Zimbabwe,2020,ZWE,15526837.0,2.317871e+10,0.0,0.0,0.0,0.0,6.440,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020-01-01
23191,Zimbabwe,2021,ZWE,15797165.0,2.514009e+10,0.0,0.0,0.0,0.0,6.963,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2021-01-01
23192,Zimbabwe,2022,ZWE,16069010.0,2.590159e+10,0.0,0.0,0.0,0.0,6.845,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-01
23193,Zimbabwe,2023,ZWE,16340778.0,0.000000e+00,0.0,0.0,0.0,0.0,7.344,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2023-01-01
23194,Zimbabwe,2024,ZWE,16634317.0,0.000000e+00,0.0,0.0,0.0,0.0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2024-01-01

## Part 4 — Summarization

In [15]:
energy_df_yr['totl_re_con'] = energy_df_yr['hydro_consumption'] + energy_df_yr['wind_consumption'] + energy_df_yr['solar_consumption']+ energy_df_yr['other_renewable_consumption']

/tmp/ipython-input-1243965412.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  energy_df_yr['totl_re_con'] = energy_df_yr['hydro_consumption'] + energy_df_yr['wind_consumption'] + energy_df_yr['solar_consumption']+ energy_df_yr['other_renewable_consumption']

In [23]:


by_cat = energy_df_yr.groupby('year')['totl_re_con'].sum().sort_values(ascending=False)
display(by_cat.head(10))

year
2024    149770.054
2023    136873.335
2022    130417.079
2021    122083.630
2020    115535.088
2019    108380.296
2018    103209.833
2017     96989.223
2016     91609.927
2015     86855.620
Name: totl_re_con, dtype: float64

## Part 5 — Visualization (Pandas + Plotly)

In [24]:
import plotly.express as px

bar_df = by_cat.head(10).reset_index()
fig = px.bar(bar_df, x=category_col, y=numeric_col, title=f'Top 10 {category_col} (interactive)')
fig.show()

## Part 6 — Reflection
- What needed adjusting when you switched datasets?
- What was easier/harder vs the workbook?
- What context/limitations should a policymaker know?

## Part 7 — ⚡ Lightning Chart Demos — Teach-Out Instructions

### What is a Lightning Demo?
A **rapid-fire mini-presentation**: 2 minutes per group. Show **one chart** + **one insight**, not your whole notebook.

### Demo Format (2 minutes)
1. **Context (15 sec):** Dataset name + 1-sentence purpose.  
2. **Chart + Insight (75–90 sec):** Show interactive Plotly chart; state one clear finding; name one wrangling step.  
3. **Caveat or Next Step (15–30 sec):** One limitation OR next idea.  
4. **Pass the mic (10 sec):** End with *“Any questions about our chart?”*

### Unique Angles
- Aggregation choice (sum vs mean, raw vs normalized).  
- Data cleaning step (conversion, deduping).  
- Encoding (bar vs line vs scatter).  
- Interactivity (facet, hover, filter).  
- Comparability (per capita vs raw counts).  
- Temporal nuance (trend vs snapshot).  

👉 If another group showed your angle, pick a different one.

### Flow for the Day
- Groups present **clustered by chart type** (bars, lines, scatter, other).  
- Instructor summarizes similarities/differences after each cluster.  
- 15 groups × 2 min = ~30 minutes + transitions = ~40 minutes.

### Presenter Checklist
- [ ] Dataset URL loads in Colab  
- [ ] Columns chosen make sense  
- [ ] One **interactive Plotly figure** with title + labels  
- [ ] Insight stated in one sentence  
- [ ] One cleaning step mentioned  

### Audience Task
After each cluster, jot 1 sentence:  
- What was **similar** across charts?  
- What was **different** (aggregation, encoding, interactivity)?  
- Which chart best supported a **policy decision**—and why?

---
### Quick Rubric (3 pts)
- **Clarity of claim (1 pt)**  
- **Method fit (1 pt)**  
- **Insight/caveat (1 pt)**  
(Bonus +0.5 for meaningful interactivity)

---
### Minimal Code Patterns

**Top-N bar:**
```python
bar_df = df.groupby(category_col)[numeric_col].sum().nlargest(10).reset_index()
fig = px.bar(bar_df, x=category_col, y=numeric_col,
             title=f"Top 10 {category_col} by {numeric_col}")
fig.show()
```

**Time series:**
```python
ts = (df.groupby(time_col)[numeric_col]
        .sum()
        .reset_index()
        .sort_values(time_col))
fig = px.line(ts, x=time_col, y=numeric_col, markers=True,
              title=f"{numeric_col} over time")
fig.show()
```

**Scatter:**
```python
fig = px.scatter(df, x=x_col, y=y_col, trendline="ols",
                 title=f"{y_col} vs {x_col}")
fig.show()
```

---