<a href="https://colab.research.google.com/github/ellenwang995/week2_pandas/blob/main/Session_2_Student_Worksheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📊 Session 2 — Student Worksheet (Pandas + Plotly)
Work in small groups. Find a CSV dataset on GitHub, load it in Colab, and adapt commands from the workbook.
Be ready to walk through your code at the end.

## Part 1 — Find a Dataset (GitHub)

In [168]:
csv_url = "https://raw.githubusercontent.com/owid/energy-data/refs/heads/master/owid-energy-data.csv"
csv_url

'https://raw.githubusercontent.com/owid/energy-data/refs/heads/master/owid-energy-data.csv'

## Part 2 — Load & Inspect

In [169]:
import pandas as pd

# Corrected URL to the raw CSV data
csv_url = "https://raw.githubusercontent.com/owid/energy-data/e93768587041dbaa2f0ea0b66af616b48c7e7364/owid-energy-data.csv"

energy = pd.read_csv(csv_url)
rows, cols = energy.shape
rows, cols

(23195, 130)

In [170]:
energy_1 = pd.DataFrame(energy)
energy_1

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,ASEAN (Ember),2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
1,ASEAN (Ember),2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
2,ASEAN (Ember),2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
3,ASEAN (Ember),2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
4,ASEAN (Ember),2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23190,Zimbabwe,2020,ZWE,15526837.0,2.317871e+10,NaN,0.0,0.0,0.0,6.440,...,0.298,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
23191,Zimbabwe,2021,ZWE,15797165.0,2.514009e+10,NaN,0.0,0.0,0.0,6.963,...,0.233,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
23192,Zimbabwe,2022,ZWE,16069010.0,2.590159e+10,NaN,0.0,0.0,0.0,6.845,...,0.336,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
23193,Zimbabwe,2023,ZWE,16340778.0,NaN,NaN,0.0,0.0,0.0,7.344,...,0.361,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
23194,Zimbabwe,2024,ZWE,16634317.0,NaN,NaN,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [171]:
energy_df = energy_1.fillna(0)

In [172]:
energy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23195 entries, 0 to 23194
Columns: 130 entries, country to wind_share_energy
dtypes: float64(127), int64(1), object(2)
memory usage: 23.0+ MB

In [173]:
energy_df.dtypes

country                    object
year                        int64
iso_code                   object
population                float64
gdp                       float64
                           ...
wind_elec_per_capita      float64
wind_electricity          float64
wind_energy_per_capita    float64
wind_share_elec           float64
wind_share_energy         float64
Length: 130, dtype: object

In [174]:
energy_df.head(10)

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,ASEAN (Ember),2000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.000,0.0
1,ASEAN (Ember),2001,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.000,0.0
2,ASEAN (Ember),2002,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.000,0.0
3,ASEAN (Ember),2003,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.000,0.0
4,ASEAN (Ember),2004,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.000,0.0
5,ASEAN (Ember),2005,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.02,0.0,0.004,0.0
6,ASEAN (Ember),2006,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.007,0.0,0.0,0.0,0.0,0.0,0.05,0.0,0.009,0.0
7,ASEAN (Ember),2007,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.007,0.0,0.0,0.0,0.0,0.0,0.06,0.0,0.010,0.0
8,ASEAN (Ember),2008,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.007,0.0,0.0,0.0,0.0,0.0,0.06,0.0,0.010,0.0
9,ASEAN (Ember),2009,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.006,0.0,0.0,0.0,0.0,0.0,0.07,0.0,0.011,0.0

In [175]:
energy_df.sample(50)

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
1283,Asia,1961,0,1.718154e+09,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
22500,Wake Island (Shift),1993,0,0.000000e+00,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
11773,Madagascar,2019,MDG,2.821951e+07,3.772465e+10,0.000,0.000,0.000,0.000,0.709,...,1.619,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
1771,Austria,1909,AUT,6.538009e+06,3.420410e+10,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
5825,Dominica,1999,DMA,6.882400e+04,3.908817e+08,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
10884,Kyrgyzstan,2015,KGZ,6.001819e+06,2.642687e+10,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
5831,Dominica,2005,DMA,6.870400e+04,4.822225e+08,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
3496,Burundi,1965,BDI,3.141333e+06,2.228969e+09,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
3124,British Virgin Islands,2011,VGB,2.869000e+04,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
3433,Burundi,1902,BDI,1.600612e+06,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
5296,Curacao,2022,CUW,1.853050e+05,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
20993,Turkmenistan,2000,TKM,4.582628e+06,1.829921e+10,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
13822,New Zealand,2005,NZL,4.134949e+06,1.270872e+11,0.000,0.000,0.000,0.000,164.452,...,0.000,0.000,69.937,0.672,1.652,147.523,0.610,399.418,1.436,0.732
4689,Colombia,2017,COL,4.813102e+07,6.340463e+11,-3.955,-0.312,157.302,7.571,29.503,...,0.013,0.002,-93.964,-0.120,0.008,0.000,0.000,0.160,0.000,0.001
511,Africa (Shift),2008,0,0.000000e+00,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
22090,Uruguay,2006,URY,3.289456e+06,4.360806e+10,0.000,0.000,0.000,0.000,15.200,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2571,Benin,1997,BEN,6.583322e+06,1.130790e+10,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
16897,Papua New Guinea,2021,PNG,1.001285e+07,0.000000e+00,0.000,0.000,0.000,0.000,0.999,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
16180,Other Europe (EI),1989,0,0.000000e+00,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
20892,Turkey,1939,TUR,1.725785e+07,4.070951e+10,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
3172,Brunei,1935,BRN,3.645900e+04,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
17427,Poland,1971,POL,3.277125e+07,2.459319e+11,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
5327,Cyprus,1993,CYP,8.259970e+05,1.217359e+10,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
8769,Guatemala,1905,GTM,1.415615e+06,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
15662,Oman,1903,OMN,3.885330e+05,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
13396,Nepal,1933,NPL,5.342207e+06,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
22846,Yemen,2018,YEM,3.408513e+07,6.527121e+10,0.000,0.000,0.000,0.000,0.000,...,13.754,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2930,Botswana,1986,BWA,1.160604e+06,3.829275e+09,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2091,Bahrain,2020,BHR,1.483026e+06,5.493734e+10,0.000,0.000,0.000,0.000,0.000,...,0.060,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
15592,Oceania,1983,0,2.406351e+07,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
18874,Somalia,1982,SOM,6.003787e+06,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
14217,Non-OECD (EI),2003,0,0.000000e+00,0.000000e+00,-0.325,-0.290,0.000,88.840,0.000,...,0.002,0.001,21.757,2.111,12.120,0.000,4.448,0.000,0.067,0.023
12077,Malta,2021,MLT,5.243350e+05,1.712204e+10,0.000,0.000,0.000,0.000,19.072,...,11.712,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
15033,Norway,2016,NOR,5.235933e+06,4.358065e+11,120.149,1.985,694.719,3.638,43.927,...,0.000,0.011,-15.865,-1.051,5.317,402.984,2.110,1015.403,1.425,0.996
3115,British Virgin Islands,2002,VGB,2.142000e+04,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
19576,Sudan,1992,SDN,2.292731e+07,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
14369,Non-OPEC (EIA),2006,0,0.000000e+00,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
21589,United Kingdom,1918,GBR,4.635269e+07,4.019422e+11,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
22460,Wake Island (EIA),1997,0,0.000000e+00,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
20281,Tanzania,1915,TZA,4.758941e+06,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
6594,Estonia,2011,EST,1.327315e+06,2.921729e+10,-41.364,-0.037,39.212,0.052,587.652,...,0.000,0.001,32.852,0.232,0.953,278.758,0.370,718.268,2.870,1.309
18423,Saudi Arabia,1956,SAU,2.106180e+06,2.121628e+10,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
13027,Morocco,2017,MAR,3.544635e+07,2.900873e+11,0.000,0.000,0.000,0.000,1.128,...,1.284,0.445,1.160,0.049,7.587,85.763,3.040,214.049,9.518,3.256
1991,Bahrain,1920,BHR,1.171430e+05,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
21042,Turks and Caicos Islands,2004,TCA,2.283600e+04,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
6586,Estonia,2003,EST,1.370799e+06,2.716024e+10,0.000,0.000,0.000,0.000,21.885,...,0.000,0.000,335.714,0.013,0.017,7.295,0.010,12.125,0.098,0.026
21765,United States,1969,USA,2.053000e+08,4.903770e+12,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
5931,EU28 (Shift),1901,0,0.000000e+00,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
20569,Tonga,1990,TON,9.966600e+04,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
10140,Israel,1921,ISR,4.638400e+05,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000

In [176]:
print(energy_df.columns)

Index(['country', 'year', 'iso_code', 'population', 'gdp',
       'biofuel_cons_change_pct', 'biofuel_cons_change_twh',
       'biofuel_cons_per_capita', 'biofuel_consumption',
       'biofuel_elec_per_capita',
       ...
       'solar_share_elec', 'solar_share_energy', 'wind_cons_change_pct',
       'wind_cons_change_twh', 'wind_consumption', 'wind_elec_per_capita',
       'wind_electricity', 'wind_energy_per_capita', 'wind_share_elec',
       'wind_share_energy'],
      dtype='object', length=130)

## Part 3 — Explore & Clean

In [177]:
energy_df[energy_df.duplicated(keep=False)]

Empty DataFrame
Columns: [country, year, iso_code, population, gdp, biofuel_cons_change_pct, biofuel_cons_change_twh, biofuel_cons_per_capita, biofuel_consumption, biofuel_elec_per_capita, biofuel_electricity, biofuel_share_elec, biofuel_share_energy, carbon_intensity_elec, coal_cons_change_pct, coal_cons_change_twh, coal_cons_per_capita, coal_consumption, coal_elec_per_capita, coal_electricity, coal_prod_change_pct, coal_prod_change_twh, coal_prod_per_capita, coal_production, coal_share_elec, coal_share_energy, electricity_demand, electricity_demand_per_capita, electricity_generation, electricity_share_energy, energy_cons_change_pct, energy_cons_change_twh, energy_per_capita, energy_per_gdp, fossil_cons_change_pct, fossil_cons_change_twh, fossil_elec_per_capita, fossil_electricity, fossil_energy_per_capita, fossil_fuel_consumption, fossil_share_elec, fossil_share_energy, gas_cons_change_pct, gas_cons_change_twh, gas_consumption, gas_elec_per_capita, gas_electricity, gas_energy_per_capita, gas_prod_change_pct, gas_prod_change_twh, gas_prod_per_capita, gas_production, gas_share_elec, gas_share_energy, greenhouse_gas_emissions, hydro_cons_change_pct, hydro_cons_change_twh, hydro_consumption, hydro_elec_per_capita, hydro_electricity, hydro_energy_per_capita, hydro_share_elec, hydro_share_energy, low_carbon_cons_change_pct, low_carbon_cons_change_twh, low_carbon_consumption, low_carbon_elec_per_capita, low_carbon_electricity, low_carbon_energy_per_capita, low_carbon_share_elec, low_carbon_share_energy, net_elec_imports, net_elec_imports_share_demand, nuclear_cons_change_pct, nuclear_cons_change_twh, nuclear_consumption, nuclear_elec_per_capita, nuclear_electricity, nuclear_energy_per_capita, nuclear_share_elec, nuclear_share_energy, oil_cons_change_pct, oil_cons_change_twh, oil_consumption, oil_elec_per_capita, oil_electricity, oil_energy_per_capita, oil_prod_change_pct, oil_prod_change_twh, oil_prod_per_capita, oil_production, oil_share_elec, oil_share_energy, other_renewable_consumption, other_renewable_electricity, other_renewable_exc_biofuel_electricity, other_renewables_cons_change_pct, other_renewables_cons_change_twh, other_renewables_elec_per_capita, other_renewables_elec_per_capita_exc_biofuel, ...]
Index: []

[0 rows x 130 columns]

In [178]:
energy_df['year_dt'] = pd.to_datetime(energy_df['year'], format='%Y')
energy_df['year_dt']

0       2000-01-01
1       2001-01-01
2       2002-01-01
3       2003-01-01
4       2004-01-01
           ...
23190   2020-01-01
23191   2021-01-01
23192   2022-01-01
23193   2023-01-01
23194   2024-01-01
Name: year_dt, Length: 23195, dtype: datetime64[ns]

In [179]:
energy_df["biofuel_consumption"]

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
23190    0.0
23191    0.0
23192    0.0
23193    0.0
23194    0.0
Name: biofuel_consumption, Length: 23195, dtype: float64

In [180]:
energy_df_yr = energy_df[energy_df['year'].between(2000, 2023)]

In [181]:
energy_df_yr

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy,year_dt
0,ASEAN (Ember),2000,0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2000-01-01
1,ASEAN (Ember),2001,0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2001-01-01
2,ASEAN (Ember),2002,0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2002-01-01
3,ASEAN (Ember),2003,0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2003-01-01
4,ASEAN (Ember),2004,0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2004-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23189,Zimbabwe,2019,ZWE,15271330.0,2.514642e+10,0.0,0.0,0.0,0.0,12.442,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2019-01-01
23190,Zimbabwe,2020,ZWE,15526837.0,2.317871e+10,0.0,0.0,0.0,0.0,6.440,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020-01-01
23191,Zimbabwe,2021,ZWE,15797165.0,2.514009e+10,0.0,0.0,0.0,0.0,6.963,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2021-01-01
23192,Zimbabwe,2022,ZWE,16069010.0,2.590159e+10,0.0,0.0,0.0,0.0,6.845,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-01
23193,Zimbabwe,2023,ZWE,16340778.0,0.000000e+00,0.0,0.0,0.0,0.0,7.344,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2023-01-01

## Part 4 — Summarization

In [182]:
energy_df_yr['totl_re_con'] = energy_df_yr['hydro_consumption'] + energy_df_yr['wind_consumption'] + energy_df_yr['solar_consumption']+ energy_df_yr['other_renewable_consumption']

/tmp/ipython-input-1243965412.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [183]:
energy_df_yr['totl_re_prod'] = energy_df_yr['hydro_electricity'] + energy_df_yr['wind_electricity'] + energy_df_yr['solar_electricity']+ energy_df_yr['other_renewable_electricity']

/tmp/ipython-input-390791244.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [184]:

by_year_prod_re = energy_df_yr.groupby('year')['totl_re_prod'].sum().sort_values(ascending=False)
display(by_year_prod_re.head(10))

year
2023    79435.998
2022    75582.051
2021    70647.177
2020    66881.532
2019    62559.487
2018    59419.609
2017    55735.347
2016    52508.716
2015    49502.840
2014    47483.114
Name: totl_re_prod, dtype: float64

In [185]:
by_year_con = energy_df_yr.groupby('year')['totl_re_con'].sum().sort_values(ascending=False)
display(by_year_con.head(10))

year
2023    136873.335
2022    130417.079
2021    122083.630
2020    115535.088
2019    108380.296
2018    103209.833
2017     96989.223
2016     91609.927
2015     86855.620
2014     83909.365
Name: totl_re_con, dtype: float64

In [186]:
by_year_prod_gas = energy_df_yr.groupby('year')['gas_electricity'].sum().sort_values(ascending=False)
display(by_year_prod_gas.head(10))

year
2023    59939.812
2022    59482.920
2021    58882.679
2019    57926.072
2020    57713.268
2018    56043.073
2017    53848.895
2016    52845.313
2015    49902.325
2012    47035.311
Name: gas_electricity, dtype: float64

In [187]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go


line_df = by_year_prod_re.reset_index()
line_df['year'] = pd.to_numeric(line_df['year'])
line_df = line_df.sort_values('year')

gas_by_year = energy_df_yr.groupby('year')['gas_electricity'].sum().reset_index()
gas_by_year['year'] = pd.to_numeric(gas_by_year['year'])

gdp_by_year = energy_df_yr.groupby('year')['gdp'].sum().reset_index()
gdp_by_year['year'] = pd.to_numeric(gdp_by_year['year'])

line_df = line_df.merge(gas_by_year, on='year', how='left')
line_df = line_df.merge(gdp_by_year, on='year', how='left')

line_df = line_df.sort_values('year')

fig = make_subplots(specs=[[{"secondary_y": True}]])

fig.add_trace(
    go.Scatter(x=line_df['year'], y=line_df['totl_re_prod'], name='Renewable Energy Production'),
    secondary_y=False
)

fig.add_trace(
    go.Scatter(x=line_df['year'], y=line_df['gas_electricity'], name='Gas Production'),
    secondary_y=False
)

fig.add_trace(
    go.Scatter(x=line_df['year'], y=line_df['gdp'], name='World GDP'),
    secondary_y=True
)

fig.update_xaxes(title_text="Year")
fig.update_yaxes(title_text="Electricity Production", secondary_y=False)
fig.update_yaxes(title_text="GDP", secondary_y=True)

fig.update_layout(title='Change Over Years: Renewable Energy Electricity Production, Gas Production, ')

fig.show()

In [190]:
import plotly.express as px

line_df = by_year_prod_re.reset_index()
line_df['year'] = pd.to_numeric(line_df['year'])
line_df = line_df.sort_values('year')

gas_by_year = energy_df_yr.groupby('year')['gas_electricity'].sum().reset_index()
gas_by_year['year'] = pd.to_numeric(gas_by_year['year'])

coal_by_year = energy_df_yr.groupby('year')['coal_electricity'].sum().reset_index()
coal_by_year['year'] = pd.to_numeric(coal_by_year['year'])

nuclear_by_year = energy_df_yr.groupby('year')['nuclear_electricity'].sum().reset_index()
nuclear_by_year['year'] = pd.to_numeric(nuclear_by_year['year'])

line_df = line_df.merge(gas_by_year, on='year', how='left')
line_df = line_df.merge(coal_by_year, on='year', how='left')
line_df = line_df.merge(nuclear_by_year, on='year', how='left')

line_df = line_df.sort_values('year')

fig = px.line(line_df,
              x='year',
              y=['totl_re_prod', 'gas_electricity', 'coal_electricity', 'nuclear_electricity'], markers = True,
              title='Change Over Years: Electricity Generation by Source',
               labels={
                  'year': 'Year',
                  'value': 'Electricity Production (TWh)',
                  'variable': 'Energy Source',
                  'totl_re_prod': 'Renewable Energy',
                  'gas_electricity': 'Gas',
                  'coal_electricity': 'Coal',
                  'nuclear_electricity': 'Nuclear'
              })
newnames = {
    'totl_re_prod': 'Renewable Energy',
    'gas_electricity': 'Gas',
    'coal_electricity': 'Coal',
    'nuclear_electricity': 'Nuclear'
}

fig.for_each_trace(lambda t: t.update(name = newnames[t.name]))

fig.show()

## Part 5 — Visualization (Pandas + Plotly)

In [50]:
import plotly.express as px

bar_df_prod_re = by_year_prod_re.head(10).reset_index()
fig = px.bar(bar_df_prod_re, x='year', y='totl_re_prod', title=f'Total Renewable Electricity Production(interactive)')
fig.show()

## Part 6 — Reflection
- What needed adjusting when you switched datasets?
- What was easier/harder vs the workbook?
- What context/limitations should a policymaker know?

## Part 7 — ⚡ Lightning Chart Demos — Teach-Out Instructions

### What is a Lightning Demo?
A **rapid-fire mini-presentation**: 2 minutes per group. Show **one chart** + **one insight**, not your whole notebook.

### Demo Format (2 minutes)
1. **Context (15 sec):** Dataset name + 1-sentence purpose.  
2. **Chart + Insight (75–90 sec):** Show interactive Plotly chart; state one clear finding; name one wrangling step.  
3. **Caveat or Next Step (15–30 sec):** One limitation OR next idea.  
4. **Pass the mic (10 sec):** End with *“Any questions about our chart?”*

### Unique Angles
- Aggregation choice (sum vs mean, raw vs normalized).  
- Data cleaning step (conversion, deduping).  
- Encoding (bar vs line vs scatter).  
- Interactivity (facet, hover, filter).  
- Comparability (per capita vs raw counts).  
- Temporal nuance (trend vs snapshot).  

👉 If another group showed your angle, pick a different one.

### Flow for the Day
- Groups present **clustered by chart type** (bars, lines, scatter, other).  
- Instructor summarizes similarities/differences after each cluster.  
- 15 groups × 2 min = ~30 minutes + transitions = ~40 minutes.

### Presenter Checklist
- [ ] Dataset URL loads in Colab  
- [ ] Columns chosen make sense  
- [ ] One **interactive Plotly figure** with title + labels  
- [ ] Insight stated in one sentence  
- [ ] One cleaning step mentioned  

### Audience Task
After each cluster, jot 1 sentence:  
- What was **similar** across charts?  
- What was **different** (aggregation, encoding, interactivity)?  
- Which chart best supported a **policy decision**—and why?

---
### Quick Rubric (3 pts)
- **Clarity of claim (1 pt)**  
- **Method fit (1 pt)**  
- **Insight/caveat (1 pt)**  
(Bonus +0.5 for meaningful interactivity)

---
### Minimal Code Patterns

**Top-N bar:**
```python
bar_df = df.groupby(category_col)[numeric_col].sum().nlargest(10).reset_index()
fig = px.bar(bar_df, x=category_col, y=numeric_col,
             title=f"Top 10 {category_col} by {numeric_col}")
fig.show()
```

**Time series:**
```python
ts = (df.groupby(time_col)[numeric_col]
        .sum()
        .reset_index()
        .sort_values(time_col))
fig = px.line(ts, x=time_col, y=numeric_col, markers=True,
              title=f"{numeric_col} over time")
fig.show()
```

**Scatter:**
```python
fig = px.scatter(df, x=x_col, y=y_col, trendline="ols",
                 title=f"{y_col} vs {x_col}")
fig.show()
```

---